### ISSUE TITLE
[ fix ] 그룹페이지 + 댓글 부분 수정

### ISSUE THREAD

**Issue by moondda** [Mile-Writings/Mile-Client#155]
## 🛠 Issue

- 전체적으로 보면서 변경된 부분, 추가되어야 하는 부분 보완하겠습니다!!
## 📝 To-do

- [x] 화면 전체 중앙정렬
- [x] 플로팅버튼 svg 깨짐 현상 해결
- [x] 댓글 없을 시 화면 구현
- [x] 플로팅 버튼 cursor pointer 적용
- [x] 헤더 내 글 모임 라우팅
- [x] 헤더 로그인/로그아웃 라우팅
- [x] 내 글 작성하기/ 플로팅 버튼 라우팅
- [x] 글모임 만들기 alert 창
