### ISSUE TITLE
[ fix ] 에디터 남은 기능 QA 잡기

### ISSUE THREAD

**Issue by se0jinYoon** [Mile-Writings/Mile-Client#249]
## 🛠 Issue

- 에디터 남은 QA 잡기
## 📝 To-do

- [ ] 엔터 두번 치고 백스페이스 눌러도 스타일 안 벗겨지게 하기
- [x] 주제, 필명 드롭다운 화살표 눌러도 열리게 구현
- [x] 글 상세페이지에서 공백 없어지는 이슈 해결하기
- [x] 글 상세페이지에서 li 태그, 인용구 앞에 마크 없어지는 이슈 해결하기
- [ ] 툴바 글자크기, 글자 색상, 글자 배경색 드롭다운 컨트롤 (하나 열리면 다른 거 닫히게 , 바깥 클릭시 닫히게)
- [x] 에셋 변경
