### ISSUE TITLE
[ fix ] 메인페이지 수정사항 반영

### ISSUE THREAD

**Issue by namdaeun** [Mile-Writings/Mile-Client#265]
## 🛠 Issue

- 메인페이지의 GUI 수정사항을 반영합니다.
## 📝 To-do

- [x] 온보딩 이미지 변경
- [x] 글 모임 버튼 스타일 변경
- [x] 마일메이커 스타일 변경
- [x] FAQ 드롭다운 데이터 변경
- [ ] 글감 막대 스타일 변경 - GUI 아직 안 나옴
- [ ] 마일메뉴얼 이미지 변경 - GUI 아직 안 나옴
