### ISSUE TITLE
[ Fix ] 공통 모달 수정사항 반영

### ISSUE THREAD

**Issue by namdaeun** [Mile-Writings/Mile-Client#278]
## 🛠 Issue

- 기존 공통모달을 다른 컴포넌트에서 사용할 때 작동하지 않던 버그를 수정합니다.
## 📝 To-do

- [x] 뒤의 검정 배경까지 같이 common으로 빼고 중앙정렬
- [x] ref 영역 다시 잡기 
- [x] 처음 모달 열리는 state를 prop에 추가
- [x] 스크롤 방지 함수 연결
