### ISSUE TITLE
[ Feat ] 에디터 뷰 변경된 api 연결

### ISSUE THREAD

**Issue by se0jinYoon** [Mile-Writings/Mile-Client#297]
## 🛠 Issue

- 에디터 뷰 변경된 api 연결
## 📝 To-do

- [ ] 필명/익명 -> default 필명으로 변경
- [ ] 임시저장 모달 -> 새로쓰기일 경우 임시저장된 글 삭제 api 연결
- [ ] 임시저장 삭제하기 api 연결
