### ISSUE TITLE
[ Init ] 초기세팅 - 필요없는 파일 삭제 및 초기세팅 마무리

### ISSUE THREAD

**Issue by ljh0608** [Mile-Writings/Mile-Client#3]
## 🛠 Issue

- 필요없는 파일 삭제하고 초기세팅 마무리
## 📝 To-do

- [x] 필요없는 파일 삭제
- [ ] router 추가
- [x] eslint 적용 확인
- [x] prettier 적용확인
- [x] 폴더 구조 단순화
