### ISSUE TITLE
[ Feat ] svg 변경사항 반영

### ISSUE THREAD

**Issue by namdaeun** [Mile-Writings/Mile-Client#307]
## 🛠 Issue

- 2차 스프린트 svg 변경사항 반영 및 자잘한 스타일 수정
## 📝 To-do

- [x] 로그인 페이지 svg 변경
- [x] 에러 페이지 svg 변경
- [x] 메인 페이지 온보딩 svg 변경
