### ISSUE TITLE
[ Refactor ] 글모임 생성 페이지 리팩토링

### ISSUE THREAD

**Issue by ljh0608** [Mile-Writings/Mile-Client#323]
## 🛠 Issue

-글모임 생성 페이지 리팩토링.

## 📝 To-do

- [ ] Outlet 적용해서 뒤로가기 기능 사용가능하도록
- [ ] 뒤로가기 해도 data가 남아있도록
- [ ] 글모임 관리 페이지 확장 가능하도록 리팩토링
