### ISSUE TITLE
[ Feat ] 관리자페이지 모임정보수정

### ISSUE THREAD

**Issue by ljh0608** [Mile-Writings/Mile-Client#354]
## 🛠 Issue

- 관리자 페이지 모임정보수정을 개발합니다. 
- 글모임 생성 페이지 몇개 수정할 것들

## 📝 To-do

- [ ] 관리자 페이지 모임정보수정 부분 개발
- [ ] 모임 생성 이미지 default url사용하도록 변경합니다.
- [ ] 글모임중복 공백포함해서 중복처리 확인합니다.
