### ISSUE TITLE
[ Fix ] 관리자 페이지 QA 해결

### ISSUE THREAD

**Issue by namdaeun** [Mile-Writings/Mile-Client#374]
## 🛠 Issue

- 관리자 페이지 QA 중 일부 해결
## 📝 To-do

- [x] 관리자 메뉴 버튼 액티브 상태일 때 컬러 수정
- [x] 전체적 페이지 중앙 정렬
- [x] 멤버 관리 - 글모임장 아이콘으로 수정
- [x] 현재 위치한 글모임 Bold로 수정
- [x] 멤버관리 뷰 멤버 없는 경우 고려하지 않음
- [x] 글 모임 수정 페이지 - 삭제 버튼 모달 추가
- [x] 멤버 삭제 버튼 테스트
- [x] 초대페이지 글모임 소개 - 잘 보임
- [x] 관리자 페이지 로그아웃시 뷰 깨짐
- [x] [메인 페이지] 캐러셀 확인
- [x] [메인 페이지] 드롭다운 드래그 안되도록 막기
- [x] 모임 정보 수정 & 글모임 생성 폰트 title8로 수정
- [x] [글 모임 생성 & 모암 정보 수정] 체크박스 선택될 때 글자 영역 바뀌는 이슈 수정
- [x] [글 모임 생성] 일러스트 사이즈 축소되는 이슈 해결
