### ISSUE TITLE
[ Fix ] QA checklist - 기획,디자인

### ISSUE THREAD

**Issue by moondda** [Mile-Writings/Mile-Client#376]
## 🛠 Issue

- 기획 측 중대한 오류 저한테 할당된거 좀 쳐낼게요
## 📝 To-do

- [x] 글감 설정 페이지네이션 오류
- [x] 글모임 접근 공개/비공개 오류
- [ ] 글감 캐러셀 오류 => 서버측에서 topicId를 숫자로 바꿔주면 잡을게요
- [x] 비공개 글모임 접근 막기
- [x] 페이지 넘어갈때 스크롤 위치
- [x] 궁금한 작가 없을 시의 워딩 수정
- [x] 글모임 사이드헤더 여백
- [x] 페이지네이션 버튼 위치
- [x] 글자 수 카운트 → 수정 이전의 데이터가 보여지는 오류
