### ISSUE TITLE
[ Fix ] 기획 디자인 QA 수정 이슈

### ISSUE THREAD

**Issue by ljh0608** [Mile-Writings/Mile-Client#377]
## 🛠 Issue

- 기획, 디자인에서 나온 QA 수정

## 📝 To-do

기획
- [x] 글모임 생성시 초대링크 변경
- [x] 초대 페이지-로그인-초대페이지로 리다이렉되도록 변경
- [x] 로그인페이지 리다이렉트 후 로그인 성공시 원래 페이지로 복귀
- [x] 글모임 생성페이지 글감생성 모달에서 글자수 제한+1로 고정하기, 입력이 완료된후 글감 작성하기 버튼 off시키기 
        모달 외부영역 클릭해도 모달이 닫히지 않도록
- [x] 글작성완료 모달 홈으로가기 누르면 글모임페이지로 이동하도록 수정
- [x] 글모임 정보수정페이지 - 수정하기 완료후 수정하기 비활성화

디자인
- [x] 페이지 이동시 스크롤 유지되는 부분 개선 (메인=>글모임생성, 글모임생성=> 메인 등등)
- [x] 글모임 생성 페이지/관리자페이지 사진 첨부 하단문구 수정
