### ISSUE TITLE
[ Fix ] 모임페이지 캐러셀 동작 수정

### ISSUE THREAD

**Issue by moondda** [Mile-Writings/Mile-Client#385]
## 🛠 Issue

-
## 📝 To-do

- [x] 첫 글감 태그 생성 후 비활성화
- [x] 캐러셀 카테고리가 6개 초과일 때 버튼 수정
- [x] 댓글 없을 케이스의 일러스트 교체
- [x] 캐러셀 넘길때 제목과 함께 내용도 넘어가게 수정
- [ ] 흐려지는 svg 랑 화살표 svg 동기화
