### ISSUE TITLE
[ feat ] 그룹페이지 캐러셀 구현

### ISSUE THREAD

**Issue by moondda** [Mile-Writings/Mile-Client#44]
## 🛠 Issue

-
## 📝 To-do

- [x] slick 도입 
- [x] nextArrow, prevArrow 커스텀 
- [x] arrow 옆에 흐려지는 svg 추가
- [x] 페이지 넘길때 첫번째 인덱스 부분 스타일링
- [x] 클릭한 인덱스 부분 스타일링
