### ISSUE TITLE
[ Feat ] Carousel 이미지 들어간 경우도 따지기

### ISSUE THREAD

**Issue by namdaeun** [Mile-Writings/Mile-Client#47]
## 🛠 Issue

- 기존에 만들어놓은 캐러셀 발전시키기
## 📝 To-do

- [x] 이미지 있을 때 텍스트 너비 조절
- [x] 마지막 슬라이드도 이미지 있으면 텍스트 너비 조절
- [x] 상수 파일에 더미 데이터 생성
