### ISSUE TITLE
[ Feat ] 에디터 남은 부분 이슈

### ISSUE THREAD

**Issue by se0jinYoon** [Mile-Writings/Mile-Client#65]
## 🛠 Issue

- 에디터 남은 부분 완료하기
- 
## 📝 To-do

- [ ] 툴바 각 아이콘 오른쪽 보더값 넣기 
- [ ] bold 버튼 누르면 색상코드 초기화 되는 이슈 해결
- [ ] 인용구 선택하고 엔터쳐도 인용구 제거되지 않는 이슈 해결
- [ ] 툴바 글자 색상과 배경색 최신값이 아닌 해당 텍스트의 값으로 수정 필요
- [ ] 툴바 위치 조정 필요
